

def create_user(): ...
def update_user(): ...
def delete_user(): ...
def read_user(): ...


def create_repo():...
def delete_repo():...
def update_repo():...
def read_repo():... 

def create_repo_access_token():...